# Generated by Django 5.1.4 on 2025-01-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlog',
            name='user',
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='portion_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
